### ISSUE TITLE
Allow positions with impossible checker alignment

### ISSUE THREAD

**Issue by andrew-buchanan** [niklasf/syzygy-tables.info#194]
Hi,

Thanks for all your work.

8/r3KPk1/8/3n4/7b/8/8/8 w - - 0 1 is marked as "invalid".

Of course it can never occur in orthodox play, but I encountered it while writing an article abut the fairy condition Bosma, and I would like to compare to orthodox play. I'm stuck now. Who cares about the history of a position as long as one can play forward from it? Isn't it more work for you to exclude such positions than it is to just process anything where forward play is defined?

"Invalid" is your term rather than FIDE term - they refer to "illegal position" if it has no sequence of legal moves from the start position but that's just a retro concept anyway. There can still be interesting forward chess to be encountered even in illegal positions. Indeed in the search for new design space for problem compositions, illegal positions are some of the simplest areas where cool stuff may remain.

The position 8/4K1k1/8/8/8/8/1P6/B7_w_-_-_0_1 is also illegal, but you have no qualms about playing forward from this one.

Here are generally ill-formed positions (by analogy with well-formed formulae in math logic)
https://syzygy-tables.info/?fen=4k3/4K3/8/8/8/8/8/8_w_-_-_0_1
https://syzygy-tables.info/?fen=4k3/8/8/8/8/8/8/P3K3_w_-_-_0_1
https://syzygy-tables.info/?fen=P3k3/8/8/8/8/8/8/4K3_w_-_-_0_1
https://syzygy-tables.info/?fen=8/8/8/8/8/8/8/3K4_w_-_-_0_1
which you can certainly exclude because one can't play chess forwards from them.

Can you please make clear precisely which valid chess positions your engine is allergic too, and ideally return to a decent state where you process all well-formed positions, irrespective of whether they are legal. 

Thanks so much for all your work,
Andrew

**Comment by niklasf** [comment]
Hi, sorry, it's been a while since this request. I just want to let you know that I do intend to improve this eventually.

There is no clean mathematical reason for the current delineation. It's rather the lowest common denominator of the particular implementations of the software involved:

* [x] ~Stockfish~ (No longer involved. This would have been a deal-breaker, as *some* positions with impossible checks are not supported)
* [x] python-chess (Supports ignoring impossible checks)
* [x] chessops
* [x] shakmaty
* [x] shakmaty-syzygy (No issue as far as i can tell)
* [x] Syzygy tablebases (Appear to include such positions)

**Comment by niklasf** [comment]
Another step towards this ... no longer rejecting such positions in the HTTP API:

* [x] lila-tablebase

**Comment by niklasf** [comment]
Hi, happy new year! It's all done, finally.
