### ISSUE TITLE
DTZ counter off by 100?

### ISSUE THREAD

**Issue by Thewodoros** [niklasf/syzygy-tables.info#360]
I've previously [asked this](https://chess.stackexchange.com/questions/46464/bug-in-syzygy-tablebases) on Chess StackExchange.

I tried to play with the position linked from the main page: [556 half-moves before the winning side can safely move a pawn](https://syzygy-tables.info/?fen=6B1/3B4/5R2/6q1/P7/1k6/8/3K4_b_-_-_0_1). Note that when you open it, the status in the top right says "Black is losing DTZ 656" instead.

By pressing "space" for the best moves you eventually reach [this position](https://syzygy-tables.info/?fen=8/2k4K/2B1q3/6R1/P7/5B2/8/8_w_-_-_0_1) which has status "White is winning DTZ 101" but offers the best move "a5 Zeroing".

If you select that move, the counter in the status jumps up to "Black is losing DTZ 114", but 14 moves later you arrive once again to [a position](https://syzygy-tables.info/?fen=3k4/6K1/2B3R1/P7/7q/5B2/8/8_w_-_-_0_1) with status "White is winning DTZ 101" and best move "a6 Zeroing".

**Comment by niklasf** [comment]
Hi. This is not a bug and also not a typo, but `DTZ50''` is a bit weird.

A `DTZ50''` of `n > 100` means that a zeroing move or checkmate can be forced in `n` or `n + 1`, or in `n - 100` or `n - 100 + 1` moves. Let's ignore the possible `+ 1` for now, which is a different topic ([rounding](https://syzygy-tables.info/metrics#dtz)).

So what about the extra `100`? The idea is that the numeric value should always indicate the result under the 50-move rule, so that min-maxing it leads to perfect play. But while the [final position of the first phase](https://syzygy-tables.info/?fen=8/2k4K/2B1q3/6R1/P7/5B2/8/8_w_-_-_0_1) is just 1 ply to zeroing, the following endgame phase is still drawn under the 50-move rule. So instead of giving it value `1`, `100` is artifically added.

Propagating this all the way back to the initial position, it gets a value of `556 + 100`, while it's really just `556` plies until the pawn move.

**Comment by Thewodoros** [comment]
Thank you, I think I understand. Of course it's pretty confusing. It would be better if such a notice (about 50-move-draw after zeroing) would be displayed explicitly in the website interface.

Do I understand correctly that this "artificial +100 ply" is added during the computations of the tablebases themselves, and not in the website interface code? Then there's probably no way to extract this information.

In that case, can you add the explanation you gave here to https://syzygy-tables.info/metrics ? Right now it is mentioned, but it's only one sentence and easy to miss. Maybe add a small section with a header like "Why can DTZ be off by 100"

**Comment by niklasf** [comment]
I tried to clarify https://syzygy-tables.info/metrics (force refresh) by splitting the DTZ section. Now the first is all about this issue (arguably the more important one), and a separate section is about rounding. Will also respond on Stackexchange.
