### ISSUE TITLE
edit/explore mode

### ISSUE THREAD

**Issue by niklasf** [niklasf/syzygy-tables.info#6]
@andrew-buchanan (niklasf/lila-tablebase#2):
> Hi many, many thanks for all your great work.
> One tiny suggestion :-) As a problem composer, most of the interaction I have with the board is seeing what the change would be if I shift a piece to a new square. However, if that shift happens to randomly correspond to a legal move, then the player to move will be flipped. This is really disconcerting.
> I am wondering if you could have two modes "Play" and "Explore". "Play" is what you have right now, but "Explore" only changes the player to move if you select the move from the menu on the right (or change the player to move explicitly at the top.

**Comment by niklasf** [comment]
I added a button for "edit mode". Please let me know if it does not work as expected or if you have any other ideas how to improve the interface for problem composers.

**Comment by andrew-buchanan** [comment]
That's great thanks! So fast!
You are featured on a chess.com blog today:
https://www.chess.com/blog/Rocky64/more-adventures-with-endgame-tablebases
Unlike Peter, I think it's better to count single moves than doubles, because more precision.
I think when you say "zeroing" you should say "win with zeroing" or whatever.
